---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a custom firewall for custom layer of irc server'
Parameters:
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Description: 'Just select the only and default VPC.'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable access to IRC server'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6667
          ToPort: 6667
          CidrIp: 0.0.0.0/0